version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
      
networks:
  webnet:

volumes:
  cache:
    driver: local
